// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comic.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PbBookInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PbBookInfo) Reset()         { *m = PbBookInfo{} }
func (m *PbBookInfo) String() string { return proto.CompactTextString(m) }
func (*PbBookInfo) ProtoMessage()    {}
func (*PbBookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f200ecbfd1cbb64d, []int{0}
}

func (m *PbBookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbBookInfo.Unmarshal(m, b)
}
func (m *PbBookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbBookInfo.Marshal(b, m, deterministic)
}
func (m *PbBookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbBookInfo.Merge(m, src)
}
func (m *PbBookInfo) XXX_Size() int {
	return xxx_messageInfo_PbBookInfo.Size(m)
}
func (m *PbBookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PbBookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PbBookInfo proto.InternalMessageInfo

func (m *PbBookInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PbBookList struct {
	Books                []*PbBookInfo `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PbBookList) Reset()         { *m = PbBookList{} }
func (m *PbBookList) String() string { return proto.CompactTextString(m) }
func (*PbBookList) ProtoMessage()    {}
func (*PbBookList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f200ecbfd1cbb64d, []int{1}
}

func (m *PbBookList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PbBookList.Unmarshal(m, b)
}
func (m *PbBookList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PbBookList.Marshal(b, m, deterministic)
}
func (m *PbBookList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PbBookList.Merge(m, src)
}
func (m *PbBookList) XXX_Size() int {
	return xxx_messageInfo_PbBookList.Size(m)
}
func (m *PbBookList) XXX_DiscardUnknown() {
	xxx_messageInfo_PbBookList.DiscardUnknown(m)
}

var xxx_messageInfo_PbBookList proto.InternalMessageInfo

func (m *PbBookList) GetBooks() []*PbBookInfo {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*PbBookInfo)(nil), "pb.PbBookInfo")
	proto.RegisterType((*PbBookList)(nil), "pb.PbBookList")
}

func init() { proto.RegisterFile("comic.proto", fileDescriptor_f200ecbfd1cbb64d) }

var fileDescriptor_f200ecbfd1cbb64d = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xcf, 0xcd,
	0x4c, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe0, 0xe2, 0x0a,
	0x48, 0x72, 0xca, 0xcf, 0xcf, 0xf6, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc,
	0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x8c, 0x60, 0x2a, 0x7c, 0x32,
	0x8b, 0x4b, 0x84, 0x54, 0xb8, 0x58, 0x93, 0xf2, 0xf3, 0xb3, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35,
	0xb8, 0x8d, 0xf8, 0xf4, 0x0a, 0x92, 0xf4, 0x10, 0x06, 0x04, 0x41, 0x24, 0x93, 0xd8, 0xc0, 0x16,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x40, 0xc5, 0x97, 0x6f, 0x00, 0x00, 0x00,
}
